server:
  port: 9001

spring:
  application:
    name: user-service

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: user-service
  health:
    reactive:
      enabled: true
    diskspace:
      enabled: true
    db:
      enabled: true