server:
  port: 9001

spring:
  application:
    name: user-service

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: user-service
  health:
    diskspace:
      enabled: true
    db:
      enabled: true